### ISSUE TITLE
Join TOS

### ISSUE THREAD

**Issue by StoneyJackson** [foss2serve/posse-stage1-mockup#4]

**Comment by kussmaul** [comment]
All done. This was difficult, but I figured it out.

**Comment by StoneyJackson** [comment]
Interesting… it didn’t move the card to done… needs investigation.

## 

Stoney Jackson
Sent with Airmail

On October 6, 2016 at 11:40:54 AM, Clif Kussmaul (notifications@github.com)
wrote:

Closed #4 https://github.com/foss2serve/posse-stage1-mockup/issues/4.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/foss2serve/posse-stage1-mockup/issues/4#event-814965001,
or mute the thread
